### ISSUE TITLE
Database Import

### ISSUE THREAD

**Issue by DreamsVoid** [PlayerRodrigoCalabrese/alexandria_emu#1]
Hi,

I'm trying to import alexandria_estaticos and I get the following error.

`sudo mysql -u root alexandria_estaticos < alexandria_estaticos.sql 
ERROR 1067 (42000) at line 24: Invalid default value for 'id'`
I am using MariaDB on Ubuntu and I am wanting to write an install tutorial for your forum... 

Thank you for any advice.

**Comment by PlayerRodrigoCalabrese** [comment]
The bug has already been fixed
